### ISSUE TITLE
I get some Webpack issues on deployment: Webpack::Rails::Manifest::ManifestLoadError in Application#home

### ISSUE THREAD

**Issue by ezbreaks** [samtgarson/vueport#8]
Hello, I'm trying to deploy the app to heroku but I got this error.

Could not load compiled manifest from /app/public/webpack/manifest.json - have you run `rake webpack:compile`? (original error No such file or directory @ rb_sysopen - /app/public/webpack/manifest.json)

[Error Photo](https://gyazo.com/5beb66bf8f110c7200406bfff3688b1d)

Can you help me to fix it? 
thank you

**Comment by samtgarson** [comment]
You need to run `npm run compile` as part of your build process in order to build the production JS bundle.

I'll update the readme to help with this issue.
