### ISSUE TITLE
Could not load manifest from webpack-dev-server

### ISSUE THREAD

**Issue by xibman** [samtgarson/vueport#9]
Hi @samtgarson I use your template, no problem in dev mode all works very well,

But in production i  have this error :  
```
Could not load manifest from webpack-dev-server at http://localhost:3808/webpack/manifest.json - is it running, and is stats-webpack-plugin loaded? (original error Connection refused - connect(2) for "localhost" port 3808)
```
I run the npm run compile before (all is good) and the manifest file is a the right place.

**Comment by samtgarson** [comment]
Hey @xibman. The fact that Rails is looking for the webpack dev server and not the compiled file suggests that the config item `config.webpack.dev_server.enabled` is returning `true` in your production environment (meaning Rails thinks the webpack development server is running).

This is set [here](https://github.com/mipearson/webpack-rails/blob/0ca9f0376bcd8528bcc6625f5b5a22ca1ee399b1/lib/webpack/railtie.rb#L37) in the WebpackRails gem to be by default:
```ruby
::Rails.env.development? || ::Rails.env.test?
```

Is your production environment running with `RAILS_ENV=production`?

**Comment by xibman** [comment]
@samtgarson thanks it works perfectly !
